// Mock data — substituir por queries Neon quando o banco estiver configurado

export interface Client {
  id: string;
  name: string;
  type: "PF" | "PJ";
  doc: string; // CPF ou CNPJ (mascarado)
  email: string;
  phone: string;
  city: string;
  state: string;
  processes: number;
  lastContact: string;
  status: "ativo" | "inativo";
  since: string;
}

export const MOCK_CLIENTS: Client[] = [
  {
    id: "1",
    name: "Maria Fernanda Costa",
    type: "PF",
    doc: "***.***.234-**",
    email: "maria.costa@email.com",
    phone: "(11) 9 8765-4321",
    city: "São Paulo",
    state: "SP",
    processes: 2,
    lastContact: "14/05/2026",
    status: "ativo",
    since: "Jan/2025",
  },
  {
    id: "2",
    name: "João Roberto Silva",
    type: "PF",
    doc: "***.***.123-**",
    email: "joao.silva@email.com",
    phone: "(11) 9 7654-3210",
    city: "Campinas",
    state: "SP",
    processes: 1,
    lastContact: "12/05/2026",
    status: "ativo",
    since: "Mar/2024",
  },
  {
    id: "3",
    name: "Construtora Horizonte Ltda",
    type: "PJ",
    doc: "12.345.678/0001-**",
    email: "juridico@horizonte.com.br",
    phone: "(11) 3456-7890",
    city: "São Paulo",
    state: "SP",
    processes: 4,
    lastContact: "10/05/2026",
    status: "ativo",
    since: "Jun/2023",
  },
  {
    id: "4",
    name: "Ana Claudia Pereira",
    type: "PF",
    doc: "***.***.456-**",
    email: "ana.pereira@email.com",
    phone: "(19) 9 9876-5432",
    city: "Ribeirão Preto",
    state: "SP",
    processes: 1,
    lastContact: "08/05/2026",
    status: "ativo",
    since: "Abr/2025",
  },
  {
    id: "5",
    name: "Carlos Eduardo Mendes",
    type: "PF",
    doc: "***.***.789-**",
    email: "carlos.mendes@email.com",
    phone: "(21) 9 8888-7777",
    city: "Rio de Janeiro",
    state: "RJ",
    processes: 0,
    lastContact: "02/04/2026",
    status: "inativo",
    since: "Nov/2023",
  },
  {
    id: "6",
    name: "Tech Solutions S/A",
    type: "PJ",
    doc: "98.765.432/0001-**",
    email: "legal@techsolutions.com.br",
    phone: "(11) 3333-4444",
    city: "São Paulo",
    state: "SP",
    processes: 3,
    lastContact: "13/05/2026",
    status: "ativo",
    since: "Fev/2024",
  },
  {
    id: "7",
    name: "Beatriz Oliveira Santos",
    type: "PF",
    doc: "***.***.321-**",
    email: "beatriz.santos@email.com",
    phone: "(31) 9 7777-6666",
    city: "Belo Horizonte",
    state: "MG",
    processes: 1,
    lastContact: "11/05/2026",
    status: "ativo",
    since: "Mai/2025",
  },
  {
    id: "8",
    name: "Rogério Alves Fernandes",
    type: "PF",
    doc: "***.***.654-**",
    email: "rogerio.fernandes@email.com",
    phone: "(41) 9 6666-5555",
    city: "Curitiba",
    state: "PR",
    processes: 2,
    lastContact: "07/05/2026",
    status: "ativo",
    since: "Set/2024",
  },
  {
    id: "9",
    name: "Imobiliária Central Ltda",
    type: "PJ",
    doc: "55.444.333/0001-**",
    email: "adm@imobiliariacentral.com.br",
    phone: "(11) 2222-3333",
    city: "São Paulo",
    state: "SP",
    processes: 5,
    lastContact: "09/05/2026",
    status: "ativo",
    since: "Jan/2023",
  },
  {
    id: "10",
    name: "Patrícia Lima Carvalho",
    type: "PF",
    doc: "***.***.987-**",
    email: "patricia.carvalho@email.com",
    phone: "(85) 9 5555-4444",
    city: "Fortaleza",
    state: "CE",
    processes: 0,
    lastContact: "15/03/2026",
    status: "inativo",
    since: "Jul/2024",
  },
  {
    id: "11",
    name: "Lucas Henrique Barros",
    type: "PF",
    doc: "***.***.147-**",
    email: "lucas.barros@email.com",
    phone: "(48) 9 4444-3333",
    city: "Florianópolis",
    state: "SC",
    processes: 1,
    lastContact: "06/05/2026",
    status: "ativo",
    since: "Out/2024",
  },
  {
    id: "12",
    name: "Grupo Empresarial Vanzolini",
    type: "PJ",
    doc: "11.222.333/0001-**",
    email: "contato@vanzolini.com.br",
    phone: "(11) 4444-5555",
    city: "São Paulo",
    state: "SP",
    processes: 6,
    lastContact: "14/05/2026",
    status: "ativo",
    since: "Mar/2022",
  },
];
